sudo: required #super user level permission
services: 
  - docker


before_install:
  - docker build -t rahul1729/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rahul1729/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-227776083601"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"