sudo: required #super user level permission
services: 
  - docker


before_install:
  - docker build -t rahul1729/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rahul1729/docker-react npm run test